#!/bin/bash

SAMPLES="$1"

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
MILA="$SCRIPT_DIR/mila"

for i in "$SAMPLES"/*.mila ; do
  j="${i%%.*}"
  echo mila "$i" -o "$j"
  "$MILA" "$i" -o "$j"
done
